/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserRouteImport } from './routes/user'
import { Route as PublicRouteImport } from './routes/public'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserReviewsRouteImport } from './routes/user/reviews'
import { Route as UserProfileRouteImport } from './routes/user/profile'
import { Route as UserBookingsRouteImport } from './routes/user/bookings'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminShowtimesRouteImport } from './routes/admin/showtimes'
import { Route as AdminRoomsRouteImport } from './routes/admin/rooms'
import { Route as AdminReviewsRouteImport } from './routes/admin/reviews'
import { Route as AdminNotificationsRouteImport } from './routes/admin/notifications'
import { Route as AdminMoviesRouteImport } from './routes/admin/movies'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminBookingsRouteImport } from './routes/admin/bookings'
import { Route as PublicShowtimesIndexRouteImport } from './routes/public/showtimes.index'
import { Route as PublicRoomsIndexRouteImport } from './routes/public/rooms.index'
import { Route as PublicMoviesIndexRouteImport } from './routes/public/movies.index'
import { Route as PublicShowtimesIdRouteImport } from './routes/public/showtimes.$id'
import { Route as PublicRoomsIdRouteImport } from './routes/public/rooms.$id'
import { Route as PublicMoviesIdRouteImport } from './routes/public/movies.$id'

const UserRoute = UserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/public',
  path: '/public',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserReviewsRoute = UserReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => UserRoute,
} as any)
const UserProfileRoute = UserProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => UserRoute,
} as any)
const UserBookingsRoute = UserBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => UserRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminShowtimesRoute = AdminShowtimesRouteImport.update({
  id: '/showtimes',
  path: '/showtimes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRoomsRoute = AdminRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMoviesRoute = AdminMoviesRouteImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const PublicShowtimesIndexRoute = PublicShowtimesIndexRouteImport.update({
  id: '/showtimes/',
  path: '/showtimes/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicRoomsIndexRoute = PublicRoomsIndexRouteImport.update({
  id: '/rooms/',
  path: '/rooms/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicMoviesIndexRoute = PublicMoviesIndexRouteImport.update({
  id: '/movies/',
  path: '/movies/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicShowtimesIdRoute = PublicShowtimesIdRouteImport.update({
  id: '/showtimes/$id',
  path: '/showtimes/$id',
  getParentRoute: () => PublicRoute,
} as any)
const PublicRoomsIdRoute = PublicRoomsIdRouteImport.update({
  id: '/rooms/$id',
  path: '/rooms/$id',
  getParentRoute: () => PublicRoute,
} as any)
const PublicMoviesIdRoute = PublicMoviesIdRouteImport.update({
  id: '/movies/$id',
  path: '/movies/$id',
  getParentRoute: () => PublicRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/public': typeof PublicRouteWithChildren
  '/user': typeof UserRouteWithChildren
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/movies': typeof AdminMoviesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/admin/showtimes': typeof AdminShowtimesRoute
  '/admin/users': typeof AdminUsersRoute
  '/user/bookings': typeof UserBookingsRoute
  '/user/profile': typeof UserProfileRoute
  '/user/reviews': typeof UserReviewsRoute
  '/public/movies/$id': typeof PublicMoviesIdRoute
  '/public/rooms/$id': typeof PublicRoomsIdRoute
  '/public/showtimes/$id': typeof PublicShowtimesIdRoute
  '/public/movies': typeof PublicMoviesIndexRoute
  '/public/rooms': typeof PublicRoomsIndexRoute
  '/public/showtimes': typeof PublicShowtimesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/public': typeof PublicRouteWithChildren
  '/user': typeof UserRouteWithChildren
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/movies': typeof AdminMoviesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/admin/showtimes': typeof AdminShowtimesRoute
  '/admin/users': typeof AdminUsersRoute
  '/user/bookings': typeof UserBookingsRoute
  '/user/profile': typeof UserProfileRoute
  '/user/reviews': typeof UserReviewsRoute
  '/public/movies/$id': typeof PublicMoviesIdRoute
  '/public/rooms/$id': typeof PublicRoomsIdRoute
  '/public/showtimes/$id': typeof PublicShowtimesIdRoute
  '/public/movies': typeof PublicMoviesIndexRoute
  '/public/rooms': typeof PublicRoomsIndexRoute
  '/public/showtimes': typeof PublicShowtimesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/public': typeof PublicRouteWithChildren
  '/user': typeof UserRouteWithChildren
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/movies': typeof AdminMoviesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/admin/showtimes': typeof AdminShowtimesRoute
  '/admin/users': typeof AdminUsersRoute
  '/user/bookings': typeof UserBookingsRoute
  '/user/profile': typeof UserProfileRoute
  '/user/reviews': typeof UserReviewsRoute
  '/public/movies/$id': typeof PublicMoviesIdRoute
  '/public/rooms/$id': typeof PublicRoomsIdRoute
  '/public/showtimes/$id': typeof PublicShowtimesIdRoute
  '/public/movies/': typeof PublicMoviesIndexRoute
  '/public/rooms/': typeof PublicRoomsIndexRoute
  '/public/showtimes/': typeof PublicShowtimesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/public'
    | '/user'
    | '/admin/bookings'
    | '/admin/dashboard'
    | '/admin/movies'
    | '/admin/notifications'
    | '/admin/reviews'
    | '/admin/rooms'
    | '/admin/showtimes'
    | '/admin/users'
    | '/user/bookings'
    | '/user/profile'
    | '/user/reviews'
    | '/public/movies/$id'
    | '/public/rooms/$id'
    | '/public/showtimes/$id'
    | '/public/movies'
    | '/public/rooms'
    | '/public/showtimes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/public'
    | '/user'
    | '/admin/bookings'
    | '/admin/dashboard'
    | '/admin/movies'
    | '/admin/notifications'
    | '/admin/reviews'
    | '/admin/rooms'
    | '/admin/showtimes'
    | '/admin/users'
    | '/user/bookings'
    | '/user/profile'
    | '/user/reviews'
    | '/public/movies/$id'
    | '/public/rooms/$id'
    | '/public/showtimes/$id'
    | '/public/movies'
    | '/public/rooms'
    | '/public/showtimes'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/public'
    | '/user'
    | '/admin/bookings'
    | '/admin/dashboard'
    | '/admin/movies'
    | '/admin/notifications'
    | '/admin/reviews'
    | '/admin/rooms'
    | '/admin/showtimes'
    | '/admin/users'
    | '/user/bookings'
    | '/user/profile'
    | '/user/reviews'
    | '/public/movies/$id'
    | '/public/rooms/$id'
    | '/public/showtimes/$id'
    | '/public/movies/'
    | '/public/rooms/'
    | '/public/showtimes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  PublicRoute: typeof PublicRouteWithChildren
  UserRoute: typeof UserRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public': {
      id: '/public'
      path: '/public'
      fullPath: '/public'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/reviews': {
      id: '/user/reviews'
      path: '/reviews'
      fullPath: '/user/reviews'
      preLoaderRoute: typeof UserReviewsRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/profile': {
      id: '/user/profile'
      path: '/profile'
      fullPath: '/user/profile'
      preLoaderRoute: typeof UserProfileRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/bookings': {
      id: '/user/bookings'
      path: '/bookings'
      fullPath: '/user/bookings'
      preLoaderRoute: typeof UserBookingsRouteImport
      parentRoute: typeof UserRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/showtimes': {
      id: '/admin/showtimes'
      path: '/showtimes'
      fullPath: '/admin/showtimes'
      preLoaderRoute: typeof AdminShowtimesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rooms': {
      id: '/admin/rooms'
      path: '/rooms'
      fullPath: '/admin/rooms'
      preLoaderRoute: typeof AdminRoomsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/movies': {
      id: '/admin/movies'
      path: '/movies'
      fullPath: '/admin/movies'
      preLoaderRoute: typeof AdminMoviesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/public/showtimes/': {
      id: '/public/showtimes/'
      path: '/showtimes'
      fullPath: '/public/showtimes'
      preLoaderRoute: typeof PublicShowtimesIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/public/rooms/': {
      id: '/public/rooms/'
      path: '/rooms'
      fullPath: '/public/rooms'
      preLoaderRoute: typeof PublicRoomsIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/public/movies/': {
      id: '/public/movies/'
      path: '/movies'
      fullPath: '/public/movies'
      preLoaderRoute: typeof PublicMoviesIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/public/showtimes/$id': {
      id: '/public/showtimes/$id'
      path: '/showtimes/$id'
      fullPath: '/public/showtimes/$id'
      preLoaderRoute: typeof PublicShowtimesIdRouteImport
      parentRoute: typeof PublicRoute
    }
    '/public/rooms/$id': {
      id: '/public/rooms/$id'
      path: '/rooms/$id'
      fullPath: '/public/rooms/$id'
      preLoaderRoute: typeof PublicRoomsIdRouteImport
      parentRoute: typeof PublicRoute
    }
    '/public/movies/$id': {
      id: '/public/movies/$id'
      path: '/movies/$id'
      fullPath: '/public/movies/$id'
      preLoaderRoute: typeof PublicMoviesIdRouteImport
      parentRoute: typeof PublicRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminMoviesRoute: typeof AdminMoviesRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminRoomsRoute: typeof AdminRoomsRoute
  AdminShowtimesRoute: typeof AdminShowtimesRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBookingsRoute: AdminBookingsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminMoviesRoute: AdminMoviesRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminRoomsRoute: AdminRoomsRoute,
  AdminShowtimesRoute: AdminShowtimesRoute,
  AdminUsersRoute: AdminUsersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PublicRouteChildren {
  PublicMoviesIdRoute: typeof PublicMoviesIdRoute
  PublicRoomsIdRoute: typeof PublicRoomsIdRoute
  PublicShowtimesIdRoute: typeof PublicShowtimesIdRoute
  PublicMoviesIndexRoute: typeof PublicMoviesIndexRoute
  PublicRoomsIndexRoute: typeof PublicRoomsIndexRoute
  PublicShowtimesIndexRoute: typeof PublicShowtimesIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicMoviesIdRoute: PublicMoviesIdRoute,
  PublicRoomsIdRoute: PublicRoomsIdRoute,
  PublicShowtimesIdRoute: PublicShowtimesIdRoute,
  PublicMoviesIndexRoute: PublicMoviesIndexRoute,
  PublicRoomsIndexRoute: PublicRoomsIndexRoute,
  PublicShowtimesIndexRoute: PublicShowtimesIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface UserRouteChildren {
  UserBookingsRoute: typeof UserBookingsRoute
  UserProfileRoute: typeof UserProfileRoute
  UserReviewsRoute: typeof UserReviewsRoute
}

const UserRouteChildren: UserRouteChildren = {
  UserBookingsRoute: UserBookingsRoute,
  UserProfileRoute: UserProfileRoute,
  UserReviewsRoute: UserReviewsRoute,
}

const UserRouteWithChildren = UserRoute._addFileChildren(UserRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  PublicRoute: PublicRouteWithChildren,
  UserRoute: UserRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
